const prod = [
    {
        _id: 1,
        image : '/assets/airpods.jfif',
        name: 'Airpods wireless bluetooth headphone',
        description : 'bluethooth technology let u connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: '89',
        countInStock: '3',
        rating: '4.5',
       newReviews :'4',
    },
     {
         _id: 2,
          image : '/assets/airpods.jfif',
        name: 'Airpods wireless bluetooth headphone',
        description : 'bluethooth technology let u connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: '89',
        countInStock: '3',
        rating: '4.5',
       newReviews :'4',
    },
      {
          _id: 3,
           image : '/assets/airpods.jfif',
        name: 'Airpods wireless bluetooth headphone',
        description : 'bluethooth technology let u connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: '89',
        countInStock: '3',
        rating: '4.5',
       newReviews :'4',
    },
      {
          _id: 4,
           image : '/assets/airpods.jfif',
        name: 'Airpods wireless bluetooth headphone',
        description : 'bluethooth technology let u connect it with compatible devices',
        brand: 'Apple',
        category: 'Electronics',
        price: '89',
        countInStock: '3',
        rating: '4.5',
       newReviews :'4',
    }
      
]
export default prod